### ISSUE TITLE
Daijisho UI sounds become silent when JDSP is active

### ISSUE THREAD

**Issue by adriansticoid** [FeralAI/o2ptweaks.app#1]
Hey there. Thank you for your work.

Daijisho is the front end that I use, and it has this clicking sounds when you navigate the UI. When the tweak is active, those sounds disappear. I tried changing all negative EQ values to zero or positive, but the issue persist. Uninstalling also does not restore it unless I reboot.

No issue with sounds from games.

**Comment by FeralAI** [comment]
Sorry for the delay. I haven't use Daijisho but I can do some testing. The next release is just about ready, so I'll see about after that.

**Comment by adriansticoid** [comment]
@FeralAI hey just following up on this. So I tried 0.2. I enabled the sound fix which installed a Magisk module, so I guess that works. But if I try to install JDSP, the app freezes, says it was successful, but nothing gets installed.

Instead, I grabbed the latest JDSP module from their Telegram group and that worked for me. I simply imported your backup for the EQ and no issues with Daijisho.

So this whole time I have O2P and JDSP installed, and then today I updated to Magisk 29.0, after reboot I got a notification from O2P that tweaks were applied. I never got this notification before. I opened the app and it's now somehow detecting JDSP because the install button turned into a switch. Daijisho sounds are gone again.

For now, I uninstalled O2P, the module for the audio fix and JDSP still installed. Everything is working smoothly.

**Comment by FeralAI** [comment]
Thanks for the update. I'll need to test out the new module and Magisk version to make sure things are working. I've got some time this weekend to dig into this.

**Comment by FeralAI** [comment]
Looks like the method I'm using for root detection isn't picking up the new Magisk version. Looking at fixing that up now and updating JamesDSP to the newest version after some testing. Should have a new version ready in the next few days.

**Comment by FeralAI** [comment]
The Magisk issue is pretty severe, so I've got it fixed and tested. I also fixed up an issue with the JamesDSP Magisk module install and updated to v6.4.

Could you please try out the new version I just released? To make sure things are working you'd probably want to uninstall the current JamesDPS Magisk module, reboot, then give it a try through the app again. If you don't want to go through all that, just verifying O2P Tweaks doesn't pop the notification and indicates ROOT in the top-right corner of the app would be great.

https://github.com/FeralAI/o2ptweaks.app/releases/tag/v0.3

**Comment by adriansticoid** [comment]
@FeralAI I installed 0.3, uninstalled JDSP version first, rebooted, and tried to install JDSP through O2P. So that seems to have installed the same module I had previously. I rebooted, no notification from O2P that tweaks were applied, Daijisho sounds are normal, and in the JDSP section, I still have that install button which seems that O2P is not detecting the JDSP module.

One more thing, I can see in the changelog that warning for the Retroid Pocket 5 was removed. I have a Pocket Mini and O2P sorta works too. Would be nice to remove the warning as well.

**Comment by FeralAI** [comment]
That behavior is all as expected.

O2P Tweaks doesn't check for the module to exist, so the option to install the JDSP module is always there. That would be a good user experience enhancement to I'll add to the backlog.

I'm planning to remove the startup warning for all devices that have been verified working in the next release.

Going to close this issue. Thanks for the reports and testing @adriansticoid!

**Comment by adriansticoid** [comment]
@FeralAI oh that was expected? I only emphasized that because like I said the install button turned into a switch at one point. But anyway, thank you for looking into this and updating the app.
